title: "Cam's AI & Policy Blog"
description: "Documenting my journey in AI and policy"
author: "Cam Clarke"
email: "" # Add your email if you want
baseurl: "" # Leave empty for GitHub Pages
url: "https://camclarke11.github.io"

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social links
github_username: camclarke11
# linkedin_username: your-linkedin
# twitter_username: your-twitter

# Build settings
markdown: kramdown

# Navigation
header_pages:
  - about.md

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Cam Clarke"
  - scope:
      path: ""
    values:
      layout: "default"

# Theme customization
show_downloads: false
google_analytics: # Add if you want analytics
logo: # Add a logo path here if you want one

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md