title: Cam's AI & Policy Blog
description: Documenting my journey in AI and policy
author: Cam Clarke
theme: jekyll-theme-cayman

# Navigation
header_pages:
  - index.md
  - about.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 